import type { Metadata } from "next";
import "../styles/globals.scss";
import { ConfigProvider } from "antd";
import { AntdRegistry } from "@ant-design/nextjs-registry";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AntdRegistry>
          <ConfigProvider
            theme={{
              components: {
                Input: {
                  colorTextPlaceholder: "#79747F",
                  borderRadius: 8,
                  colorBorder: "#ECECEC",
                },
                Checkbox: {
                  colorTextDescription: "#79747F",
                  colorText: "#79747F",
                  colorBorder: "#C8C5CD",
                  fontSize: 12,
                },
                Button: {
                  colorPrimary: "#8D7FC7",
                  borderRadius: 30,
                },
              },
            }}
          >
            {children}
          </ConfigProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
